version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php -d zend_extension=xdebug.so ./service/driver/worker.php"

temporal:
  address: "127.0.0.1:7233"
  activities:
    num_workers: 4

logs:
  level: debug
  mode: development
