rpc:
  listen: "tcp://127.0.0.1:6001"

server:
  command: "php worker.php"
  relay: "pipes"
  relay_timeout: "20s"

version: "2.7"
grpc:
  listen: "tcp://127.0.0.1:9001"
  proto:
    - "proto/common.proto"
    - "proto/backend.proto"
    - "proto/bucket.proto"
    - "proto/credentials.proto"
    - "proto/info.proto"
    - "proto/project.proto"
    - "proto/table.proto"
    - "proto/workspace.proto"
  max_send_msg_size: 50
  max_recv_msg_size: 50
  max_connection_idle: 0s
  max_connection_age: 0s
  max_connection_age_grace: 0s
  max_concurrent_streams: 10
  ping_time: 1s
  timeout: 200s
  pool:
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60
