version: "3.5"
services:
  production: &prod
    build:
      context: .
      args:
        - GITHUB_OAUTH_TOKEN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    environment:
      - DEBUG
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
      - BUILD_PREFIX
      - TERADATA_HOST
      - TERADATA_USERNAME
      - TERADATA_PASSWORD
      - TERADATA_PORT
      - TERADATA_ROOT_DATABASE
  dev: &dev
    <<: *prod
    image: keboola/php-storage-driver-teradata
    volumes:
      - ./:/code
    network_mode: host
  dev-xdebug:
    <<: *dev
    build: etc/docker/xdebug
  controllerWorker:
    <<: *dev
    command:
      - /usr/local/bin/rr
      - serve
      - -c
      - /code/.rr.controller.yaml
  driverWorker:
    <<: *dev
    build: etc/docker/xdebug
    command:
      - /usr/local/bin/rr
      - serve
      - -c
      - /code/.rr.driver.yaml
    environment:
      PHP_IDE_CONFIG: serverName=application.loc
      XDEBUG_CONFIG: remote_host=host.docker.internal max_nesting_level=250 remote_enable=1 remote_connect_back=0 var_display_max_depth=5 idekey='PHPSTORM'
