version: '3'
services:
  production: &prod
    build:
      context: .
      args:
        - GITHUB_OAUTH_TOKEN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    environment:
      - DEBUG
      - ABS_ACCOUNT_NAME
      - ABS_ACCOUNT_KEY
      - ABS_SAS_TOKEN
      - ABS_CONTAINER_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
      - BUILD_PREFIX
      - TERADATA_HOST
      - TERADATA_USERNAME
      - TERADATA_PASSWORD
      - TERADATA_PORT
      - TERADATA_ROOT_DATABASE
      - STORAGE_TYPE
  dev: &dev
    <<: *prod
    image: keboola/php-storage-driver-teradata
    network_mode: host
    volumes:
      - ./:/code
  dev-xdebug:
    <<: *dev
    build: etc/docker/xdebug
volumes:
  exa-volume:
